POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "video 2",
  "desc": "Meu segundo video!",
  "duration": 280
}

###

GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/046efc3e-1521-40a2-a0ad-9d159d07c9
Content-Type: application/json

{
  "title": "teste",
  "desc": "teste",
  "duration": 280
}

###

DELETE  http://localhost:3000/videos/497091bc-f57f-4ec4-947a-a9be03e10749