POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "video 2",
  "desc": "Meu segundo video!",
  "duration": 280
}

###

GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/6637ff05-d29c-414b-baba-606ee219e4f6
Content-Type: application/json

{
  "title": "teste",
  "desc": "teste",
  "duration": 280
}

###

DELETE  http://localhost:3000/videos/6637ff05-d29c-414b-baba-606ee219e4f6